# Site settings
title: s/buy/make/
motto: s/buy/make/
email: henry.hinnefeld@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  s/buy/make/ is a blog about making things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hinnefe2.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  hinnefe2
linkedin_username:  henryhinnefeld

# Build settings
markdown: kramdown
